version: '3.4'

services:
  caddy:
    image: abiosoft/caddy
    volumes:
      - ../:/srv
      - ./caddy/Caddyfile:/etc/Caddyfile
      - ~/.caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - ACME_AGREE=false

  db:
    image: mariadb
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'

  php-fpm:
    build:
      context: ./php-fpm/
      dockerfile: Dockerfile-ubuntu
      args:
        TIMEZONE: America/Sao_Paulo
        PHP_MEMORY_LIMIT: 512M
        MAX_UPLOAD: 50M
        PHP_MAX_FILE_UPLOAD: 200
        PHP_MAX_POST: 100M
    volumes:
      - ../:/www
      
  
volumes:
  dbdata: